# oeitam

test_commands = [ "create megaproject Work1 | 1all projects that relate to Work at Intel go here",
                  "create project project_one @Work1 | this is the first project I created",
                  "create megaproject Work2 | 2all projects that relate to Work at Intel go here",
                  "create project project_two @Work2 | this is the first project I created",
                  "create project project_three @Work1 | this is the first project I created",
                  "create project project_four @Work2 | this is the first project I created",
                  "create project project_five @Work1 | this is the first project I created",
                  #"turn_on",
                  "task @project_one | this is what you need to do on project one",
                  "task @project_one | another this is what you need to do on project one",
                  "task @project_two | this is what you need to do on project two",
                  "task @project_two | second this is what you need to do on project two",
                  "task @project_two | second this is what you need to do on project two",
                  "start @0000 | one this is some activity related to a task",
                  "start @0000 | two this is some activity related to a task",
                  "start @0000 | three this is some activity related to a task",
                  "start @0000 | four this is some activity related to a task",
                  "start @0000 | five this is some activity related to a task",
                  "start @0000 | six this is some activity related to a task",
                  "start @0000 | seven this is some activity related to a task",
                  "create megaproject Work11 | 11all projects that relate to Work at Intel go here",
                  "create project project_one1 @Work11 | this is the first project I created",
                  "create megaproject Work21 | 21all projects that relate to Work at Intel go here",
                  "create project project_two1 @Work21 | this is the first project I created",
                  "create project project_three1 @Work11 | this is the first project I created",
                  "create project project_four1 @Work21 | this is the first project I created",
                  "create project project_five1 @Work11 | this is the first project I created",
                  #"turn_on",
                  "task @project_one | 1this is what you need to do on project one",
                  "task @project_one | 1another this is what you need to do on project one",
                  "task @project_two | 1this is what you need to do on project two",
                  "task @project_two1 | 1second this is what you need to do on project two",
                  "task @project_two | 1third this is what you need to do on project two",
                  "start @0000 | one1 this is some activity related to a task",
                  "start @0000 | two1 this is some activity related to a task",
                  "start @0000 | three1 this is some activity related to a task",
                  "start @0000 | four1 this is some activity related to a task",
                  "start @0000 | five1 this is some activity related to a task",
                  "start @0000 | six1 this is some activity related to a task",
                  "start @0000 | seven1 this is some activity related to a task",
                  #
                  'die',
                  ]


test_responses = []

