
print('test_defs_sections.py')


test_commands_s3= [
    #'start @103 fromcb',
    'delete @135',
    'delete @137',
    'delete @143',
    'delete @139',
    'list activity',
    'die'
    ]

test_commands_s1 = [
    'create megaproject MP01 | 101',
    #
    'create project P01 @MP01 | 102',
    'create project P02 @MP01 | 103',
    #
    'task @P01 | task #01 @P01 > 104',
    'task @P01 | task #02 @P01 > 105',
    'task @P01 | task #03 @P01 > 106',
    'task @P01 | task #04 @P01 > 107',
    'task @P01 | task #05 @P01 > 108',
    #
    'task @P02 state OnHold | task #06 @P02 > 109',
    'task @P02 | task #07 @P02 > 110',
    'task @P02 | task #08 @P02 > 111',
    'task @P02 | task #09 @P02 > 112',
    'task @P02 | task #10 @P02 > 113',
    #
    'start @P01 state Dormant | activity #01 > 114',
    'list @114',
    'halt @114',
    'start @P01 | activity #02 > 115',
    'start @P01 | activity #03 > 116',
    'start @P01 | activity #04 > 117',
    'start @P01 | activity #05 > 118',
    'start @110 | activity #06 > 119',
    'start @110 | activity #07 > 120',
    'start @110 | activity #08 > 121',
    'start @110 | activity #09 > 122',
    'start @110 | activity #10 > 123',
    #
    'start @107 | activity #06 > 124',
    'start @107 | activity #07 > 125',
    'start @108 | activity #08 > 126',
    'start @108 | activity #09 > 127',
    'start @108 | activity #10 > 128',
    #
    'tag @114 AI01',
    'tag @117 AI02',
    'tag @117 BLA1',
    'tag @117 BLA2',
    'tag @116 AI03',
    #
    'tag @108 AI01',
    'tag @105 AI02',
    'tag @105 BLA1',
    'tag @105 BLA2',
    'tag @106 AI03'
    ]

test_commands_s2 = [    
    'list megaproject',
    'list project',
    'list task state all sort AI',
    'list activity sort AI state all',
    #
    'list @101 hier',
    #'list @102',
    #'list @119 hier', # activity under task
    #'list @116 hier', # activity under project
    #'list @113',      # task
    #'list @113 hier', # task with hierarchy
    'list task',
    'list activity for project P01',
    'list task for project P02',
    'list activity for task @110',
    'list @102 hier state all',
    'list @103 hier state all',
    'die',
    'die',
    #'help',
    #'list shortcut',
    #'t | bla bla bla',
    #'set max_width value 3',
    #'list activity',
    #'list parameter',
    #'timedelta',
    #'edit @14624  | one',
    #'edit @14625  | two',
    #'edit @14626  | three',
    #'edit @14628  | four',
    #'edit @14638  | five',
    #'edit @14640  | six',
    #'set columns_print_style 1',
    #'list activity',
    #'push @14640 @14628',
    #'list activity',
    #'die',
    #'set columns_print_style 1',
    #'list task',
    #'push @14476 @14521',
    #'list task',
    #'start @project_one | this is a test activity',
    #'start @10852 | this is a test activity',
    #'start @10674 | this is a test activity',
    #'task @project_one | this is task at project one',
    #'list activity',
    #'list task',
    #'die',
    #"ci",
    #"co",
    #"co",
    #"list activity state OnHold",
    #"list megaproject state On",
    #"list project state OnHold",
    #"list task state OnHold",
    #"list activity col Start_Date drange bot top",
    #"list activity ww 43",
    #"list activity ww 43 state OnHold",
    #"list activity state OnHold ww 43",
    #"list activity ww 43",
    #'list activity col Start_Date drange 17ww35.Sun 17ww39',
    #'today | help bla bla',
    #'sleep @11540 17ww50',
    #'sleep @11540 17ww50.Sun',
    #'die',
    #'cont @10673',
    #'sleep @10673 plus 99',
    #'list task state Dormant',
    #'list activity state Dormant',
    #'timedelta 21',
    #'task @11369 | 123456789',
    #'timedelta 20',
    #'task @11369 | 123456789',
    #'timedelta 19',
    #'task @11369 | 123456789',
    #'timedelta 18',
    #'task @11369 | 123456789',
    #'timedelta 17',
    #'task @11369 | 123456789',
    #'timedelta 16',
    #'task @11369 | 123456789',
    #'timedelta 15',
    #'task @11369 | 123456789',
    #'timedelta 14',
    #'task @11369 | 123456789',
    #'timedelta 13',
    #'task @11369 | 123456789',
    #'timedelta 12',
    #'task @11369 | 123456789',
    #'timedelta 11',
    #'task @11369 | 123456789',
    #'timedelta 10',
    #'task @11369 | 123456789',
    #'timedelta 9',
    #'task @11369 | 123456789',
    #'timedelta 8',
    #'task @11369 | 123456789',
    #'timedelta 7',
    #'task @11369 | 123456789',
    #'timedelta 6',
    #'task @11369 | 123456789',
    #'timedelta 5',
    #'task @11369 | 123456789',
    #'timedelta 4',
    #'task @11369 | 123456789',
    #'timedelta 3',
    #'task @11369 | 123456789',
    #'timedelta 2',
    #'task @11369 | 123456789',
    #'list task state all for project project_two listall',
    # THIS IS FROM THE CLIPBOARD
    #'create megaproject CB1 fromcb',
    #'online', 
    #'list shortcut',
    #'t',
    #'t | ',
    #'t|',
    #'list activity',
    # a =14628 t = 14505 p = 13800 m = 14195
    #'list @14628',
    #'edit @14628 | two this is new ',
    #'list @14628',
    #'list @14505',
    #'edit @14505 | two this is new ',
    #'list @14505',
    #'list @13800',
    #'edit @13800 | two this is new ',
    #'list @13800',
    #'list @14195',
    #'edit @14195 | two this is new ',
    #'list @14195',
    'help',
    'die',
    'set columns_print_style 1',
    'set list_resp_row_limit 3',
    'timedelta 1',
    'start @P1  |blabla',
    'halt @14538',
    'cont @14538 | blalkshnnnweiojhfahha  hasdofih ',
    'list activity state all',
    'die',
    #'create project P1 @CB1 |blabla',
    #'task @P1  |blabla',
    #'start @P1  |blabla',
    'cont @14512 | cont text',
    'cont @14512',
    'cont @14513 | cont text',
    'cont @14514 | cont text',
    'list project state all',
    'list task state all',
    'list activity state all',
    'halt @14512 | halt text',
    'halt @14513 | halt text',
    'halt @14514 | halt text',
    'list project state all',
    'list task state all',
    'list activity state all',
    'sleep @14512 plus 88 | sleep text',
    'sleep @14513 plus 88 | sleep text',
    'sleep @14514 plus 88 | sleep text',
    'list project state all',
    'list task state all',
    'list activity state all',
    'die',
    #'set list_resp_row_limit 2',
    'list parameter',
    'set columns_print_style 1',
    'list megaproject',
    'list project',
    'list task',
    'list activity',
    'die',
    'list task',
    #'task for project project_two',
    'bla bla',
    'die',
    'kil',
    'list task col Start_Date drange 18ww13.Thu top',
    'list task lastdays 17',
    'list',
    'die',
    'list @14287',
    'list @14304',
    'swap @14287 @14304',
    #'halt @14304',
    #'list @14304',
    'die',
    'list parameter',
    'set list_resp_row_limit 20',
    'list parameter',
    'die',
    'online',
    'start @project_one | bla bla bla bla 0987654',
    #'list',
    'die',
    'list @14304',
    'halt @14304',
    'list @14304',
    'die',
    'task @project_one | bla bla bla 12345',
    'die',
    'list tag',
    'die',
    #'list megaproject columns',
    #'list project columns',
    #'list task columns',
    #'list activity columns',
    #'die',
    'list task week 18ww08',
    'list activity week 18ww08',
    'die',
    'list activity col Start_Date drange 18ww08.Sun 18ww08.Sat',
    'die',
    'sleep @14193 20180301',
    #'online',
    'list wakeup',
    'list @14193',
    'cont @14193',
    'list @14193',
    'die',
    #'list wakeup',
    #'help @',
    #'create project test1 @Work2',
    #'create project test2 @Work2',
    #'list task for project test1',
    #'die',
    #'halt @10661',
    #'online',
    #'cont @10673',
    #'list project',
    #'list activity',
    #'online',
    #'die',
    #'create list @10677 @10678 @10679',
    #'list list',
    #'list list',
    #'timedelta',
    #'timedelta off',
    #'timedelta 10',
    #'timedelta',
    #'list shortcut',
    #'timedelta 749',
    #'start @project_one | bla bla bla',
    'list activity',
    #'die',
    'help timedelta',
    'die',
    'create shortcut | ["simple_substitution", "co", "start @10758 | checking out - go home"]',
    #'list shortcut',
    'delete shortcut 8',
    'list shortcut',
    #'die',
    'set list_resp_row_limit value 3',
    'task @project_one | some time, yes',
    'list task',
    'timedelta',
    'timedelta 48',
    'timedelta',
    'task @project_one | some time, yes',
    'list task',
    'timedelta off',
    'timedelta',
    'task @project_one | some time, yes',
    'list task',
    #'die',

    'task @project_one tag QQQ1| some task',
    'start @13849 tag QQQ1 | some activity',
    'create project MYPROJ @Work1 tag QQQ1 | some proj desc',
    'list tag QQQ1',
    #'die',
    'create list @10677 @10678 @10679',
    'tag list TAG_FOR_LIST',
    'list tag TAG_FOR_LIST',
    'list tag XXX',
    #'die',
    'list task tag tag_for_proj_one',
    'list activity tag tag_for_proj_one',
    'list project tag tag_for_proj_one',
    "list activity tag tag_for_proj_one col Start_Date drange bot 17ww20",
    "list activity col Start_Date drange bot 17ww20 tag tag_for_proj_one",
    #'die',

    'tag @10673 tag_two',
    'tag @13399 tag_for_proj_one',
    'tag @13373 tag_for_proj_one',
    #'list @13399',
    #'die',
    'tag project UNIQUE tag_for_proj_one',
    'tag project UNIQUE tag_for_proj_one',
    'tag project UNIQUE tag_for_proj_one',
    'list tag tag_for_proj_one',
    'list tag',
    'list activity',
    #'die',
    'untag project UNIQUE tag_for_proj_one',
    'untag project UNIQUE',
    #'die',
    'tag @10673 tag_one',
    'tag @10673 tag_one',
    'tag @10673 tag_one',
    'list @10673',
    'untag @10673 tag_one',
    'list @10673',
    'untag @10673',
    'list @10673',

    'tag @13367 tag_one',
    'tag @13367 tag_one',
    'tag @13367 tag_one',
    'list @13367',
    'untag @13367 tag_one',
    'list @13367',
    'untag @13367',
    'list @13367',

    'tag @13399 tag_one',
    'tag @13399 tag_one',
    'tag @13399 tag_one',
    'list @13399',
    'untag @13399 tag_one',
    'list @13399',
    'untag @13399',
    'list @13399',

    #'die',
    'help 10673',
    'help list',
    #'die',
    'create shortcut | ["pipe_substitution", "lulu", "start @12969"]',
    'lulu | this other funny text',
    'list activity',
    #'create project UNIQUE @Work11 | soem',
    #'die',
    'task @12969 | task for project project_five1',
    'start @UNIQUE | this is activity for unique',
    'list activity',
    'list task',
    #'die',
    'list shortcut',
    #'create shortcut | ["simple_substitution", "co", "start @10758 | checking out - go home"]',
    'list shortcut',
    'delete shortcut 5',
    'list shortcut',
    #'die',
    'list parameter',
    'set max_width value 51',
    'list parameter',
    'set max_width value 50',
    'list parameter',
    #'die',
    'list task',
    'set list_resp_row_limit value 5',
    'list task',
    'set list_resp_row_limit value 15',
    'list task',
    #'die',
    'list task state all for project test1',
    #'die',
    'list task state all for project test2',
    'move task from test1 to test2',
    'list task state all for project test1',
    'list task state all for project test2',
    'move task from test2 to test1',
    'list task state all for project test1',
    'list task state all for project test2',
    'move task from test1 to test2 state OnHold',
    'list task state all for project test1',
    'list task state all for project test2',
    'move task from test2 to test1 state OnHold',
    'list task state all for project test1',
    'list task state all for project test2',
    #'die',
    'create list @10677 @10678 @10679',
    'online',
    'create list @10661 @10662 @10672',
    'move list to test2',
    'list task for project test2',
    'create list @10661 @10662 @10672',
    'move list to test1',
    'list task for project test1',
    'move @10661 to test2',
    'list task for project test2',
    'move @10661 to test1',
    'list task for project test1',
    #'die',
    'cont @11540',
    'cont @10687',
    'cont @10673',
    'sleep @11540 17ww50',
    'sleep @10687 20171205',
    'sleep @10673 plus 88',
    'sleep @10673',
    'list @11540',
    'list @10687',
    'list @10673',
    #'die',
    'help',
    #'list project',
    #'die',
    #'list activity state all col Start_Date drange 17ww35.Sun 17ww39.Mon',
    #'list activity col Start_Date drange 17ww35.Sun 17ww39.Mon state OnHold',
    #'list activity col Start_Date drange 17ww35.Sun 17ww39.Mon',
    #'list activity ww 43',
    #"die",
    #"start @00000000 | two this is some activity related to a taask",
    "create megaproject Work2 | 2all projects that relate to Work at Intel go here",
    "create megaproject Work2 | 2all projects that relate to Work at Intel go here",
    "create megaproject Work2 | 2all projects that relate to Work at Intel go here",
    "create project project_two @Work2 | this is the first project I created",
    "ci",
    "co",
    #"die",
    "create project project_three @Work1 | this is the first project I created",
    "create project project_four @Work2 | this is the first project I created",
    "create project project_five @Work1 | this is the first project I created",
    "task @project_one | 1this is what you need to do on project one",
    "task @project_one | 1another this is what you need to do on project one",
    "task @project_two | 1this is what you need to do on project two",
    "task @project_two1 | 1second this is what you need to do on project two",
    "task @project_two | 1third this is what you need to do on project two",
    #"die",
    "start @00000000 | two this is some activity related to a taask",
    "start @00000000 | three this is some activity related to a taask",
    "start @00000000 | four this is some activity related to a taask",
    "start @00000000 | five this is some activity related to a taask",
    "start @00000000 | six this is some activity related to a taask",
    "start @00000000 | seven this is some activity related to a taask",
    "start @0 | some activity, not project or task",
    #"die",
    "create megaproject Work2 | 2all projects that relate to Work at Intel go here",
    "create project project_two @Work2 | this is the first project I created",
    "create project project_three @Work1 | this is the first project I created",
    "create project project_four @Work2 | this is the first project I created",
    "create project project_five @Work1 | this is the first project I created",
    # "turn_on",
    "task @project_one | another this is what you need to do on project one",
    "task @project_two | this is what you need to do on project two",
    "task @project_two | second this is what you need to do on project two",
    "task @project_two | second this is what you need to do on project two",
    "start @00000000 | one this is some activity related to a taask",
    "stop @00000000",
    "cont @00000000",
    "list @00000000",
    "list @00000000",
    "list @00000000",
    "start @00000000 | two this is some activity related to a taask",
    "start @00000000 | three this is some activity related to a taask",
    "start @00000000 | four this is some activity related to a taask",
    "start @00000000 | five this is some activity related to a taask",
    "start @00000000 | six this is some activity related to a taask",
    "start @00000000 | seven this is some activity related to a taask",
    "create megaproject Work11 | 11all projects that relate to Work at Intel go here",
    "create project project_one1 @Work11 | this is the first project I created",
    "create megaproject Work21 | 21all projects that relate to Work at Intel go here",
    "create project project_two1 @Work21 | this is the first project I created",
    "create project project_three1 @Work11 | this is the first project I created",
    "create project project_four1 @Work21 | this is the first project I created",
    "list @00000000",
    "list @00000000",
    "list @00000000",
    "create project project_five1 @Work11 | this is the first project I created",
    # "turn_on",
    "task @project_one | 1this is what you need to do on project one",
    "task @project_one | 1another this is what you need to do on project one",
    "task @project_two | 1this is what you need to do on project two",
    "task @project_two1 | 1second this is what you need to do on project two",
    "task @project_two | 1third this is what you need to do on project two",
    "start @00000000 | one1 this is some activity related to a taask",
    "start @00000000 | two1 this is some activity related to a taask",
    "start @00000000 | three1 this is some activity related to a taask",
    # "list @00000000",
    "start @00000000 | four1 this is some activity related to a taask",
    "start @00000000 | five1 this is some activity related to a taask",
    "start @00000000 | six1 this is some activity related to a taask",
    "start @00000000 | seven1 this is some activity related to a taask",
    "list search | ww 26",
    "list activity ww 17",
    "list activity ww 18",
    "list activity ww 19",
    "list activity ww 20",
    "list task ww 17",
    "list task ww 18",
    "list task ww 19",
    "list task ww 20",
    #"die",
    "list megaproject columns",
    "list project columns",
    "list task columns",
    "list activity columns",
    "list megaproject states",
    "list project states",
    "list task states",
    "list activity states",
    #"die"
    "list megaproject for project project_one",
    "list project for megaproject Work1",
    "list task for project project_two",
    "list activity for project project_one",
    "list",
    "list activity for task @2334",
    #"die",
    "create megaproject Work1 | 1all projects that relate to Work at Intel go here",
    "list activity col Start_Date drange 17ww17.Sun 17ww20.Mon",
    "list activity col Start_Date drange 17ww17 17ww20.Mon",
    "list activity col Start_Date drange 17ww17.Sun 17ww20",
    "list activity col Start_Date drange 17ww17 17ww20",
    "list activity col Start_Date drange bot 17ww20.Mon",
    "list activity col Start_Date drange bot 17ww20",
    "list activity col Start_Date drange 17ww17.Sun top",
    "list activity col Start_Date drange 17ww17 top",
    "list activity col Start_Date drange bot top",
    #"die",
    "list megaproject col ID irange 2569 2631",
    "list megaproject col ID irange 2569 top",
    "list megaproject col ID irange bot 2631",
    "list megaproject col ID irange bot top",

    "halt @00000000",
    "stop @00000000",
    "cont @00000000",
    "list @00000000",
    #"die",
    #"turn on",
    "list megaproject",
    "list",
    "list",
    "list megaproject col Name is Work1",
    "list megaproject",
    "list",
    "list",
    "list",
    "list",
    "list megaproject limit 30",
    "list",
    "list",
    "list",
    "list",
    "list",
    "list project",
    "list",
    "list",
    "list project col Name is project_two",
    "list",
    "list",
    "list task",
    "list",
    "list",
    "list task col PROJECT is project_two",
    "list",
    "list",
    "list activity",
    "list",
    "list",
    "list activity col PROJECT is 1498",
    "list",
    "list activity col Description inc one",
    "list",
    "list activity col PROJECT not 1498",
    "list",
    "list activity col PROJECT ninc 1498",
    "list",
    "list",
    "list task",
    "list activity",
    #"die",
    "create project project_one @Work1 | this is the first project I created",
    "task @project_one | this is what you need to do on project one",
    "start @00000000 | one this is some activity related to a taask",
    "stop @00000000",
    "stop @00000000",
    "stop @00000000",
    "stop @00000000",
    "halt @00000000",
    "halt @00000000",
    "halt @00000000",
    "cont @00000000",
    "halt @00000000",
    "create megaproject Work2 | 2all projects that relate to Work at Intel go here",
    "create project project_two @Work2 | this is the first project I created",
    "create project project_three @Work1 | this is the first project I created",
    "create project project_four @Work2 | this is the first project I created",
    "create project project_five @Work1 | this is the first project I created",
    #"turn_on",
    "task @project_one | another this is what you need to do on project one",
    "task @project_two | this is what you need to do on project two",
    "task @project_two | second this is what you need to do on project two",
    "task @project_two | second this is what you need to do on project two",
    "start @00000000 | one this is some activity related to a taask",
    "stop @00000000",
    "cont @00000000",
    "list @00000000",
    "list @00000000",
    "list @00000000",
    "start @00000000 | two this is some activity related to a taask",
    "start @00000000 | three this is some activity related to a taask",
    "start @00000000 | four this is some activity related to a taask",
    "start @00000000 | five this is some activity related to a taask",
    "start @00000000 | six this is some activity related to a taask",
    "start @00000000 | seven this is some activity related to a taask",
    "create megaproject Work11 | 11all projects that relate to Work at Intel go here",
    "create project project_one1 @Work11 | this is the first project I created",
    "create megaproject Work21 | 21all projects that relate to Work at Intel go here",
    "create project project_two1 @Work21 | this is the first project I created",
    "create project project_three1 @Work11 | this is the first project I created",
    "create project project_four1 @Work21 | this is the first project I created",
    "list @00000000",
    "list @00000000",
    "list @00000000",
    "create project project_five1 @Work11 | this is the first project I created",
    #"turn_on",
    "task @project_one | 1this is what you need to do on project one",
    "task @project_one | 1another this is what you need to do on project one",
    "task @project_two | 1this is what you need to do on project two",
    "task @project_two1 | 1second this is what you need to do on project two",
    "task @project_two | 1third this is what you need to do on project two",
    "start @00000000 | one1 this is some activity related to a taask",
    "start @00000000 | two1 this is some activity related to a taask",
    "start @00000000 | three1 this is some activity related to a taask",
    # "list @00000000",
    "start @00000000 | four1 this is some activity related to a taask",
    "start @00000000 | five1 this is some activity related to a taask",
    "start @00000000 | six1 this is some activity related to a taask",
    "start @00000000 | seven1 this is some activity related to a taask",
    "stop @00000000",
    "stop @00000000",
    "stop @00000000",
    "list @00000000",
    "stop @00000000",
    "stop @00000000",
    "stop @00000000",
    "list @00000000",
    "cont @00000000",
    "cont @00000000",
    "cont @00000000",
    "halt @00000000",
    "halt @00000000",
    "halt @00000000",
    "online",
    "sleep @00000000",
    "sleep @00000000",
    "sleep @00000000",
    "sleep @00000000",
    "sleep @00000000",
    "sleep @00000000",
    #
    'die',
    'kil',
]
